CHANGELOG.md
README.md
lib/Auth/Process/COmanageDbClient.php
www/idp_callback.php

- Enabled target_new
- Small typo fixes in queries
- Updated documentation
- Moved variables from placeholder state to configuration

SSP_Enable_target_new_Configurize_urn_registry_urls

---

CHANGELOG.md
README.md
lib/Auth/Process/COmanageDbClient.php

- Restored Self Sign up functionality
- Moved voRoles to configuration.

Self_sign_up_Config

---

lib/Auth/Process/COmanageDbClient.php

Fetch and assembly entitlements from COU title and affiliation

COU_title_and_affiliation_to_entitlements

---

lib/Auth/Process/COmanageDbClient.php

- Create entitlement with group name cou_name:admins and roles member/owner
- Refactored the code that assemble the roles into entitlements

COU_admin_member_owner_role

---

lib/Auth/Process/COmanageDbClient.php
lib/Auth/Process/COmanageRestClient.php

- Match psr-4 guideline
- Added namespaces
- Changed array notation

Add support for SSP v1.17

---

lib/Auth/Process/COmanageDbClient.php
www/idp_callback.php

- Moved all the logic that retrieves user's data from COmanage to a separate function named retrieveCOPersonData
- The callback resumes the state on the retrieveCOPersonData
SSP 1.14 compatible change

Target_new_resume_from_class_function

---

lib/Auth/Process/COmanageDbClient.php
www/idp_callback.php

- Moved all the logic that retrieves user's data from COmanage to a separate function named retrieveCOPersonData
- The callback resumes the state on the retrieveCOPersonData
SSP 1.17 compatible change

Target_new_resume_from_class_function_v1_17

---

lib/Auth/Process/COmanageDbClient.php

- Added target_new support in self_sign_up flow
- Fixed wrong evaluation of admin member|owner role

Minor_error_fixes_114

---

lib/Auth/Process/COmanageDbClient.php

- Added target_new support in self_sign_up flow
- Fixed wrong evaluation of admin member|owner role

Minor_error_fixes

---

README.md
lib/Auth/Process/COmanageDbClient.php

Construct eduPersonEntitlements with VO hierarchy. For example:
```
urn:mace:foo.org:group:vo.parent.example.eu:vo.ioigoume.child.example.eu:role=member#foo.org
urn:mace:foo.org:group:vo.parent.example.eu:vo.child.example.eu:vo.child.child.example.eu:role=member#foo.org
```

FEATURE_entitlements_cou_nested_AARC_guideline

---

lib/Auth/Process/COmanageDbClient.php

- Fetch COPerson memberships in one query.
- Fix wrong calculation of entitlements if the user is an admin but has no affiliation in a COU.

RCIAM-343_getCous_query_in_attrauthcomanage_is_not_working_properly

---

README.md
lib/Auth/Process/COmanageDbClient.php

- Replaced voPrefix with groupPrefix.
- Fixed faulty condition in entitlement construction.
- Fixed uninitialized variables.
- Minor code fixes.

BUG_get_users_profile_integration_errors

---

lib/Auth/Process/COmanageDbClient.php

- Refactored getProfile query.
- Construct,add voPersonVerifiedEmail into state.

RCIAM-245_propagate_vopersonverified_to_SP

---

README.md
lib/Auth/Process/COmanageDbClient.php

Add configuration for importing Terms Aggreement into the State

ADD_get_terms_aggreement

---

README.md
lib/Auth/Process/COmanageDbClient.php

- Make getCert configurable.
- Indentation fixes.

IMPROVEMENT_make_cert_check_configuration

---

CHANGELOG.md
README.md
lib/Auth/Process/COmanageDbClient.php

Add option to skip voWhitelist checks, if `voWhitelist` is `null`

Extend voWhitelist functionality

---

lib/Auth/Process/COmanageDbClient.php

Refactor validation of configuration parameters.

RCIAM-414_SSPmod_attrauthcomanage_fix_configuration_parser

---

CHANGELOG.md
README.md
lib/Auth/Process/COmanageDbClient.php

Refactor Identifier calculation.
Styling improvements.

IMPROVENENT_refactor_org_identifier_calculation

---

CHANGELOG.md
README.md
dictionaries/attrauthcomanage.definition.json
lib/Auth/Process/COmanageDbClient.php
templates/exception.tpl.php

Feature community signup noaffiliation

REBASE_feature/community-signup-noaffiliation_1.5

---

README.md
lib/Auth/Process/COmanageDbClient.php

- Fixed default values for optional configuration variables.
- Refactored README.md.

Fix_default_values_for_optional_conf_variables

---

CHANGELOG.md
Models/AUP.md
README.md
lib/Auth/Process/COmanageDbClient.php

Construct AUP model and add in the state - `$state['rciamAttributes']['aup']`. 
Add COPerson ID in the state - `$state['rciamAttributes']['userId']`.

RCIAM-428_AUP_model_construct

---

lib/Auth/Process/COmanageDbClient.php

Fixed buggy filtering in AUP construct function

AUP_model_construct_fix_buggy_cou_name_filtering

---

CHANGELOG.md
README.md
lib/Attributes/SshPublicKey.php
lib/Auth/Process/COmanageDbClient.php

Add support for retrieving ssh keys from user's profile

Feature - sshPublicKey attribute

---

docs/model/aup.md

AUP_model_documentation_improvement

---

docs/model/aup.md
lib/Auth/Process/COmanageDbClient.php

Moved aup_id field name to aupId

AUP_model_fields_must_be_camel_case

---

CHANGELOG.md
README.md
docs/model/aup.md
lib/Attributes/SshPublicKey.php
lib/Auth/Process/COmanageDbClient.php

Communtiy signup affiliation sync with release-1.5.4

Communtiy-signup-affiliation-SYNC

---

CHANGELOG.md
lib/Auth/Process/COmanageDbClient.php

Calculation of AUP model was skipped when user had no COU/Group memberships

BUG_skipping_aup_when_no_membership

---

CHANGELOG.md
README.md
dictionaries/attrauthcomanage.definition.json
lib/Attributes/SshPublicKey.php
lib/Auth/Process/COmanageDbClient.php
templates/exception.tpl.php
www/idp_callback.php

Features from release-1.5 to release-2.x

Features_from_release1_5_to_release_2_x

---

CHANGELOG.md
lib/Auth/Process/COmanageDbClient.php

- Fix agreed aup revision with null value.
- Minor style changes.

BUG_unable_to_handle_aup_revision_null

---

CHANGELOG.md
lib/Auth/Process/COmanageDbClient.php

Fix agreed aup revision with null value evalueated falsely

Sync_with_release-1.5.6

---

CHANGELOG.md
lib/Attributes/SshPublicKey.php
lib/Auth/Process/COmanageDbClient.php

BUG_fix_namespace_errors

---

CHANGELOG.md
lib/Auth/Process/COmanageDbClient.php

Apply missing namespace changes

Namespace Error

---

CHANGELOG.md
lib/Auth/Process/COmanageDbClient.php

Remove empty Attributes edupersonentitlement when no memberships

Bug_empty_attribute_edupersonentitlement

---

CHANGELOG.md
lib/Auth/Process/COmanageDbClient.php

Skip merge if not entitlements exist

Skip_merge_when_no_entitlements

---

lib/Auth/Process/COmanageDbClient.php
lib/Enums/OrgIdentityStatusEnum.php

Add org_identity status.
Modify query to exclude the removed ones from fetch profile

Handle_removed_org_identities

---

CHANGELOG.md
lib/Auth/Process/COmanageDbClient.php

On error message return friendly user message and not the stack trace

Render_friendly_error_message_not_the_stack_trace

---

CHANGELOG.md
dictionaries/noty.definition.json
lib/Attributes/SshPublicKey.php
lib/Auth/Process/COmanageDbClient.php
lib/Enrollment/PetitionHandler.php
lib/User/AuthenticationEventHandler.php
lib/User/OrgIdentity.php
templates/noty.tpl.php

- Refactor OrgIdentity state construction
- Fix throwing errors

Error_handling_fixes

---

CHANGELOG.md
lib/Auth/Process/COmanageDbClient.php
lib/User/OrgIdentity.php

Enable job functionality for comanage (orgIdentity)

---

lib/Auth/Process/COmanageDbClient.php

Fixed entitlements for nested non-member roles

Fix_nested_group_role_entitlement

---

lib/Auth/Process/COmanageDbClient.php

Exclude custom role from nested entitlements

Exclude_custom_role_from_nested_entitlements
